### PR TITLE
Add Git Workflow instructions to README.md file

### PR DESCRIPTION
**Pull request by stephencapper**

### CODE REVIEW

**Comment by stephencapper** [comment]
Adding link to [implementation task](https://trello.com/c/A41ZtVPG) in Trello

**Review by JamesClover — APPROVED** [review]
LGTM

**Review by Liaaang858 — APPROVED** [review]
LGTM - great step by step!

**Comment by Liaaang858** [comment]
[Implementation - ReadMe Documentation for Git Workflow](https://trello.com/c/A41ZtVPG/24-implementation-readme-documentation-for-git-workflow)

**Pull request merged**
