### PR TITLE
Server - API request and response routing functionality

### PR DESCRIPTION
**Pull request by stephencapper**
Added function to server that takes requests of any method from client to url '/api/<documented API url>', adds authentication assuming that .env and .config files are set up correctly, sends the requests to the API and returns responses or errors to the client.

Note that server must also be running using `npm run server-dev` command for this to work.

Also updated package.json dependencies to include dotenv and .gitignore to include .env and .config files

Tested server functionality with postman for a a range of get, post and push requests.

### CODE REVIEW

**Comment by stephencapper** [comment]
[Implementation - Server](https://trello.com/c/KtXqF1OD/25-implementation-server)

**Comment by stephencapper** [comment]
Looking at the files here, maybe I need to add package-lock.json to .gitignore before finalizing this merge?

**Comment by stephencapper** [comment]
[User Story - Development Server](https://trello.com/c/J4BG8Ocq/17-user-story-development-server)

**Review by Liaaang858 — APPROVED** [review]
lgtm - approach is pretty cool!

**Comment by stephencapper** [comment]
@Liaaang858 do you know if it is ok to have the package-lock.json in the merge, or is that something that I should be including in .gitignore first?

**Pull request merged**
