### PR TITLE
R&R: Complete Product Breakdown, and Review Search, and CSS refactor

### PR DESCRIPTION
**Pull request by stephencapper**
Completed Product Breakdown component requirements (see linked user story for detailed requirements).

Did some CSS cleanup to get the overall module format looking closer to right.

Started to refactor from using central CSS stylesheet to using module specific style sheets

Edit: also added the review search component and automatic filtering of the review list by searched term if term has 3 or more characters, meeting all requirements for Review Search (1.2.7 of requirements). Details in User Story I will link in comments.

Edit 2: completed the CSS refactor so that all reviews and rating css is in modules. Began overhauling css for my component to better match visual requirement document.

### CODE REVIEW

**Comment by stephencapper** [comment]
[Implementation: R&R Product Breakdown](https://trello.com/c/1i4yCG7r/80-implementation-rr-product-breakdown)

**Comment by stephencapper** [comment]
[User Story - R&R 1.2.5 Product Breakdown](https://trello.com/c/C8iu0UIf/35-user-story-rr-125-product-breakdown)

**Comment by stephencapper** [comment]
[Implementation - R&R Keyword Search](https://trello.com/c/7HgaqVGy/85-implementation-rr-keyword-search)

**Comment by stephencapper** [comment]
[User Story - R&R 1.2.7 Keyword Search - Low Priority!](https://trello.com/c/1kww6Pyp/37-user-story-rr-127-keyword-search-low-priority)

**Review by Liaaang858 — APPROVED** [review]
Approved - Product Breakdown and Search logic looks good. Additional reviewal of span classNames, and css organization.

**Pull request merged**
