### PR TITLE
R&R: Complete ReviewTile & ReviewList Requirements

### PR DESCRIPTION
**Pull request by stephencapper**
Complete remaining review tile requirements, including:
- photos (if applicable) as thumbnails with ability to click to make show on top of page in a dialogue box, with a close button
- product recommend icon and comment, and response section, if each are applicable
- Helpful and report buttons, which make applicable API put requests and store that user has already registered an opinion in local storage

Additional cleanup:
- updates to ARIA roles and labels to make accessibility tests pass 100%
- updated index.jsx so that we are only rendering one id=root div in the html elements and to prevent react console.log error message we were getting for [using render which is no longer supported](https://react.dev/blog/2022/03/08/react-18-upgrade-guide#updates-to-client-rendering-apis)

Edit: Also have completed remaining ReviewList requirements:
- 2 reviews load initially (or following filter or sort), with more reviews button to see additional reviews
- if size of overall module would not fit on page, review list becomes scrollable

### CODE REVIEW

**Comment by stephencapper** [comment]
[User Story - R&R 1.2.2 Individual Review Tile](https://trello.com/c/bKo2N38r/21-user-story-rr-122-individual-review-tile)

**Comment by stephencapper** [comment]
[Implementation: R&R Individual Review Tile](https://trello.com/c/FyuymNLs/69-implementation-rr-individual-review-tile)

**Comment by stephencapper** [comment]
[Implementation - R&R: Complete ReviewList requirements](https://trello.com/c/WSmGCwsI/78-implementation-rr-complete-reviewlist-requirements)

**Comment by stephencapper** [comment]
[User Story - R&R 1.2.1 Reviews List](https://trello.com/c/8T5wD9hZ/19-user-story-rr-121-reviews-list)

**Review by JamesClover — APPROVED** [review]
It looks great. I really like the inclusion of semantic HTML elements!

**Pull request merged**
